/* Gli eventi di CronoItalia.
 *
 * year   : anno storico con segno. L'anno 0 non esiste (1 a.C. -> 1 d.C.).
 * endYear: per i fatti che durano (guerre, cantieri, epidemie).
 * type   : battaglia | guerra | viaggio | fondazione | scoperta | disastro | cultura
 * path   : tappe [lon,lat] disegnate come rotta animata.
 */

const EVENTI = [

/* ==================== Prima di Roma ==================== */
{id:"otzi",year:-3300,lat:46.78,lon:10.84,type:"scoperta",title:"L'uomo del Similaun",
 description:"Un uomo muore colpito da una freccia su un valico a 3.200 metri. Il ghiaccio lo restituirà intatto nel 1991, con arco, ascia di rame e l'ultimo pasto ancora nello stomaco."},
{id:"nuraghi",year:-1800,endYear:-1000,lat:39.70,lon:8.99,type:"fondazione",title:"I nuraghi di Sardegna",
 description:"Migliaia di torri di pietra a secco punteggiano l'isola. Su Nuraxi di Barumini è il cuore di un villaggio fortificato che resisterà per secoli."},
{id:"terramare",year:-1600,lat:44.80,lon:10.60,type:"fondazione",title:"Le terramare padane",
 description:"Villaggi su palafitte, circondati da argini e fossati, ordinati come piccole città: la pianura tra Po ed Enza è tra le zone più popolate d'Europa."},
{id:"villanoviani",year:-900,lat:44.49,lon:11.34,type:"cultura",title:"La cultura villanoviana",
 description:"Sepolture a pozzetto con urne biconiche segnano la nascita, tra Bologna e la Toscana, del popolo che diventerà etrusco."},
{id:"roma-fondazione",year:-753,lat:41.90,lon:12.49,type:"fondazione",title:"La fondazione di Roma",
 description:"La tradizione fissa al 21 aprile il solco tracciato da Romolo sul Palatino. L'archeologia conferma capanne e mura proprio in quel secolo."},
{id:"cuma",year:-740,lat:40.85,lon:14.05,type:"fondazione",title:"Cuma, la prima colonia greca",
 description:"Coloni dell'Eubea sbarcano nel golfo: portano l'alfabeto, la vite e l'idea stessa di città. Da qui la scrittura risalirà tutta la penisola."},
{id:"siracusa",year:-734,lat:37.08,lon:15.28,type:"fondazione",title:"Siracusa",
 description:"Corinzi si stabiliscono nell'isola di Ortigia. Diventerà la città più potente dell'Occidente greco, rivale di Atene e Cartagine."},
{id:"sibari",year:-720,lat:39.72,lon:16.45,type:"fondazione",title:"Sibari",
 description:"Sulla piana dello Ionio nasce la città che darà al mondo la parola \"sibarita\": ricchezza tale da diventare proverbiale, e da attirare l'odio dei vicini."},
{id:"taranto",year:-706,lat:40.47,lon:17.24,type:"fondazione",title:"Taranto spartana",
 description:"L'unica colonia fondata da Sparta: figli irregolari cacciati dalla madrepatria trovano nel golfo il porto migliore dello Ionio."},
{id:"tarquinia",year:-680,lat:42.25,lon:11.76,type:"cultura",title:"Le tombe dipinte di Tarquinia",
 description:"Sotto le colline, camere funerarie affrescate con banchetti, danze e tuffatori: l'aldilà etrusco è una festa, non un lutto."},
{id:"paestum",year:-600,lat:40.42,lon:15.01,type:"fondazione",title:"Poseidonia",
 description:"Coloni da Sibari fondano la città dei tre templi dorici, che resteranno in piedi duemilacinquecento anni in mezzo alla piana malarica."},
{id:"kainua",year:-500,lat:44.34,lon:11.20,type:"fondazione",title:"Kainua, la città a scacchiera",
 description:"Gli Etruschi progettano a tavolino una città padana con strade ortogonali e fognature: un piano regolatore prima dei Romani."},
{id:"alalia",year:-540,lat:42.10,lon:9.51,type:"battaglia",title:"La battaglia del Mare Sardo",
 description:"Etruschi e Cartaginesi contro i Focei di Alalia. Vincono i coloni, ma perdono tante navi da doversene andare: il Tirreno resta etrusco."},

/* ==================== Roma repubblicana ==================== */
{id:"repubblica",year:-509,lat:41.89,lon:12.48,type:"fondazione",title:"Nasce la Repubblica",
 description:"Cacciato Tarquinio il Superbo, Roma sostituisce il re con due consoli che durano un anno. Il potere diventa qualcosa che si restituisce."},
{id:"veio",year:-396,lat:42.02,lon:12.39,type:"battaglia",title:"La presa di Veio",
 description:"Dopo dieci anni d'assedio cade la grande rivale etrusca, a poche ore di marcia da Roma. Il territorio romano raddoppia di colpo."},
{id:"allia",year:-390,lat:41.98,lon:12.60,type:"battaglia",title:"I Galli sull'Allia",
 description:"L'esercito romano si sfalda in mezza giornata e Brenno entra in città. \"Guai ai vinti\": Roma pagherà il riscatto e non dimenticherà più."},
{id:"caudine",year:-321,lat:41.10,lon:14.62,type:"battaglia",title:"Le Forche Caudine",
 description:"Chiuse le due gole, i Sanniti costringono due legioni ad arrendersi e a passare sotto il giogo. L'umiliazione entra nella lingua italiana."},
{id:"appia",year:-312,lat:41.75,lon:12.60,type:"fondazione",title:"La via Appia",
 description:"Appio Claudio fa lastricare la strada che scende verso Capua e poi verso Brindisi: la regina viarum tiene insieme il dominio meglio di un esercito.",
 path:[[12.49,41.90],[14.21,41.10],[14.78,41.13],[17.24,40.47],[17.94,40.63]]},
{id:"eraclea",year:-280,lat:40.22,lon:16.67,type:"battaglia",title:"Pirro a Eraclea",
 description:"Gli elefanti da guerra sbaragliano i Romani, ma le perdite del re epirota sono enormi: da qui la \"vittoria di Pirro\"."},
{id:"benevento-275",year:-275,lat:41.13,lon:14.78,type:"battaglia",title:"Pirro se ne va",
 description:"Fermato a Maleventum, Pirro riparte per l'Epiro. I Romani ribattezzano il luogo Beneventum: il Sud italico è loro."},
{id:"prima-punica",year:-264,endYear:-241,lat:38.19,lon:15.55,type:"guerra",title:"La prima guerra punica",
 description:"Ventitré anni di guerra per la Sicilia, combattuti quasi tutti in mare da un popolo che non aveva flotta e se la costruisce copiando una nave nemica."},
{id:"egadi",year:-241,lat:37.95,lon:12.20,type:"battaglia",title:"Le Egadi",
 description:"La flotta romana affonda quella punica al largo di Favignana. Cartagine cede la Sicilia: nasce la prima provincia."},
{id:"annibale",year:-218,endYear:-201,lat:44.90,lon:7.30,type:"viaggio",title:"Annibale passa le Alpi",
 description:"Con trentasettemila uomini e gli elefanti scende in Italia da nord, dove nessuno lo aspetta, e per quindici anni nessuno riuscirà a cacciarlo.",
 path:[[7.30,44.90],[9.70,45.00],[12.10,43.13],[16.13,41.30],[16.50,39.20]]},
{id:"trebbia",year:-218,lat:45.00,lon:9.70,type:"battaglia",title:"La Trebbia",
 description:"Annibale attira i Romani a guadare il fiume gelato all'alba, digiuni, e poi li prende alle spalle con la cavalleria nascosta."},
{id:"trasimeno",year:-217,lat:43.13,lon:12.10,type:"battaglia",title:"Il lago Trasimeno",
 description:"Nella nebbia del mattino l'esercito consolare marcia in colonna tra il lago e i monti: l'imboscata più grande della storia antica."},
{id:"canne",year:-216,lat:41.30,lon:16.13,type:"battaglia",title:"Canne",
 description:"Il centro cede apposta, le ali si chiudono: ottantamila Romani accerchiati in poche ore. La manovra si studia ancora nelle accademie militari."},
{id:"metauro",year:-207,lat:43.75,lon:13.05,type:"battaglia",title:"Il Metauro",
 description:"Asdrubale scende in Italia per raggiungere il fratello: i Romani lo intercettano prima. La testa del fratello viene gettata nel campo di Annibale."},
{id:"cisalpina",year:-190,endYear:-170,lat:44.80,lon:10.33,type:"fondazione",title:"Colonie nella pianura padana",
 description:"Piacenza, Cremona, Bologna, Parma, Modena, Aquileia: una catena di colonie e la via Emilia trasformano la Gallia Cisalpina in Italia."},
{id:"gracchi",year:-133,lat:41.89,lon:12.48,type:"cultura",title:"I Gracchi e la terra",
 description:"Tiberio propone di ridistribuire l'ager publicus ai contadini rovinati dalla guerra. Verrà ucciso a bastonate in Campidoglio: la politica romana scopre il sangue."},
{id:"guerra-sociale",year:-91,endYear:-88,lat:42.14,lon:13.84,type:"guerra",title:"La guerra sociale",
 description:"Gli alleati italici si ribellano per ottenere la cittadinanza e fondano a Corfinio una loro capitale, Italia. Perdono la guerra e ottengono la cittadinanza."},
{id:"spartaco",year:-73,endYear:-71,lat:41.10,lon:14.21,type:"guerra",title:"La rivolta di Spartaco",
 description:"Settantaquattro gladiatori fuggono da una scuola di Capua e diventano un esercito di decine di migliaia. Finirà con seimila croci lungo l'Appia.",
 path:[[14.21,41.10],[14.43,40.82],[16.50,39.30],[15.80,40.64],[13.60,41.30]]},
{id:"rubicone",year:-49,lat:44.10,lon:12.40,type:"guerra",title:"Il Rubicone",
 description:"Cesare varca con una legione il confine dell'Italia in armi. \"Il dado è tratto\": è guerra civile, e la Repubblica non si riprenderà."},
{id:"cesare-idi",year:-44,lat:41.89,lon:12.48,type:"battaglia",title:"Le Idi di marzo",
 description:"Ventitré pugnalate alla Curia di Pompeo. I congiurati credono di salvare la Repubblica e ne firmano la fine."},

/* ==================== Impero ==================== */
{id:"augusto",year:-27,lat:41.89,lon:12.48,type:"fondazione",title:"Augusto e il principato",
 description:"Ottaviano restituisce formalmente i poteri al Senato e riceve il titolo di Augusto. La Repubblica resta in piedi come facciata per tre secoli."},
{id:"regiones",year:-7,lat:41.89,lon:12.48,type:"cultura",title:"Le undici regioni d'Italia",
 description:"Augusto divide l'Italia in regiones, dalla Transpadana alla Calabria: la prima carta amministrativa della penisola, che l'Ottocento riprenderà."},
{id:"ara-pacis",year:-9,lat:41.91,lon:12.48,type:"cultura",title:"L'Ara Pacis",
 description:"Un altare di marmo racconta a rilievo la famiglia imperiale in processione: la pace come programma politico, scolpita."},
{id:"pompei",year:79,lat:40.75,lon:14.49,type:"disastro",title:"L'eruzione del Vesuvio",
 description:"In due giorni Pompei, Ercolano e Stabia scompaiono sotto pomici e flussi piroclastici. Plinio il Giovane ne scriverà il primo resoconto vulcanologico."},
{id:"colosseo",year:80,lat:41.89,lon:12.49,type:"fondazione",title:"Il Colosseo",
 description:"Cinquantamila spettatori, ottanta ingressi numerati, un velario mosso dai marinai della flotta: cento giorni di giochi per l'inaugurazione."},
{id:"traiano",year:113,lat:41.89,lon:12.48,type:"cultura",title:"La colonna Traiana",
 description:"Duecento metri di fregio a spirale raccontano la conquista della Dacia: un reportage di guerra avvolto attorno a una colonna."},
{id:"villa-adriana",year:125,lat:41.94,lon:12.77,type:"fondazione",title:"Villa Adriana",
 description:"A Tivoli l'imperatore si fa costruire un mondo in miniatura: copie dei luoghi che ha amato nell'Impero, disposte in centoventi ettari."},
{id:"ostia",year:150,lat:41.75,lon:12.29,type:"cultura",title:"Ostia, il porto di Roma",
 description:"Magazzini, case a più piani, bar con il bancone di marmo: la città che nutre la capitale con il grano d'Africa e d'Egitto."},
{id:"milvio",year:312,lat:41.93,lon:12.47,type:"battaglia",title:"Ponte Milvio",
 description:"Costantino sconfigge Massenzio alle porte di Roma. La tradizione vuole che abbia fatto dipingere il monogramma di Cristo sugli scudi."},
{id:"editto-milano",year:313,lat:45.46,lon:9.19,type:"cultura",title:"L'editto di Milano",
 description:"Costantino e Licinio concedono libertà di culto a tutti. In pochi decenni la religione perseguitata diventerà quella dell'Impero."},
{id:"ambrogio",year:386,lat:45.46,lon:9.19,type:"cultura",title:"Ambrogio a Milano",
 description:"Il vescovo tiene testa alla corte imperiale e inventa il canto responsoriale: la Chiesa d'Occidente scopre di poter dire no all'imperatore."},
{id:"alarico",year:410,lat:41.89,lon:12.48,type:"disastro",title:"Il sacco di Roma",
 description:"I Visigoti entrano dalla porta Salaria e saccheggiano per tre giorni. La città non veniva presa da ottocento anni: l'Impero pare finito, e in Africa Agostino comincia La città di Dio."},
{id:"attila",year:452,lat:45.77,lon:13.37,type:"disastro",title:"Attila ad Aquileia",
 description:"La grande città dell'alto Adriatico viene rasa al suolo. I profughi si rifugiano nelle lagune: è una delle radici di Venezia."},
{id:"ravenna-mosaici",year:450,lat:44.42,lon:12.20,type:"cultura",title:"I mosaici di Ravenna",
 description:"Galla Placidia, poi Teodorico, poi Giustiniano: in un secolo la capitale d'Occidente si riempie di cieli d'oro e di stelle blu."},
{id:"odoacre",year:476,lat:44.42,lon:12.20,type:"guerra",title:"La fine dell'Impero d'Occidente",
 description:"Odoacre depone Romolo Augustolo e rispedisce le insegne a Costantinopoli: non serve più un imperatore in Italia. Nessuno, sul momento, se ne accorge davvero."},
{id:"teodorico",year:493,lat:44.42,lon:12.20,type:"fondazione",title:"Il regno di Teodorico",
 description:"Il re ostrogoto governa da Ravenna con funzionari romani e leggi romane: trent'anni di convivenza fra Goti e Italici, poi tutto si rompe."},
{id:"benedetto",year:529,lat:41.49,lon:13.81,type:"fondazione",title:"Montecassino",
 description:"Benedetto da Norcia scrive una Regola breve e ragionevole: ora et labora. Da quelle poche pagine nasceranno migliaia di monasteri europei."},
{id:"guerra-gotica",year:535,endYear:553,lat:41.89,lon:12.48,type:"guerra",title:"La guerra gotica",
 description:"Diciotto anni di assedi fra Bizantini e Goti riducono Roma a poche migliaia di abitanti e spezzano l'Italia tardoantica."},
{id:"tagina",year:552,lat:43.23,lon:12.79,type:"battaglia",title:"Tagina",
 description:"Narsete annienta l'esercito di Totila presso Gualdo Tadino. Il regno ostrogoto finisce, ma l'Italia è devastata e senza difese."},

/* ==================== Longobardi, Bizantini, Franchi ==================== */
{id:"longobardi",year:568,lat:46.09,lon:13.43,type:"guerra",title:"I Longobardi in Italia",
 description:"Alboino entra dal Friuli e in pochi anni occupa la pianura. L'Italia si divide fra terre longobarde e corridoi bizantini: durerà due secoli.",
 path:[[13.43,46.09],[10.99,45.44],[9.16,45.19]]},
{id:"gregorio",year:590,lat:41.89,lon:12.48,type:"cultura",title:"Gregorio Magno",
 description:"Un papa che tratta con i Longobardi, organizza l'annona e manda missionari in Inghilterra: il papato comincia a fare le veci dell'Impero."},
{id:"teodolinda",year:603,lat:45.58,lon:9.27,type:"cultura",title:"Teodolinda a Monza",
 description:"La regina longobarda si converte al cattolicesimo e fa costruire la basilica: la corona ferrea diventerà simbolo dei re d'Italia."},
{id:"bobbio",year:614,lat:44.77,lon:9.39,type:"fondazione",title:"Colombano a Bobbio",
 description:"Monaci irlandesi fondano in val Trebbia un monastero che diventerà una delle biblioteche più ricche d'Europa."},
{id:"venezia-origini",year:697,lat:45.44,lon:12.33,type:"fondazione",title:"Il primo doge",
 description:"Le comunità lagunari si danno un capo eletto. Da isole di pescatori nasce la città che dominerà l'Adriatico per mille anni."},
{id:"liutprando",year:730,lat:45.19,lon:9.16,type:"cultura",title:"Le leggi di Liutprando",
 description:"Il re longobardo aggiorna ogni anno l'editto di Rotari: proprietà, matrimoni, risarcimenti. Il diritto scritto torna in Italia."},
{id:"carlo-magno",year:774,lat:45.19,lon:9.16,type:"guerra",title:"Carlo Magno re d'Italia",
 description:"Assediata Pavia, il re dei Franchi depone Desiderio e cinge la corona longobarda. L'Italia entra nell'orbita europea.",
 path:[[7.32,45.10],[9.16,45.19]]},
{id:"natale-800",year:800,lat:41.90,lon:12.45,type:"cultura",title:"L'incoronazione di Carlo",
 description:"A San Pietro, la notte di Natale, il papa gli mette in testa la corona imperiale. Nasce un Impero d'Occidente che dirà di essere il seguito di Roma."},
{id:"arabi-mazara",year:827,lat:37.65,lon:12.59,type:"guerra",title:"Gli Arabi sbarcano a Mazara",
 description:"Diecimila uomini partiti dall'Ifriqiya iniziano una conquista che durerà settant'anni e cambierà l'agricoltura, la cucina e la lingua dell'isola."},
{id:"san-marco",year:828,lat:45.43,lon:12.34,type:"viaggio",title:"Il corpo di san Marco",
 description:"Due mercanti veneziani trafugano ad Alessandria le reliquie dell'evangelista nascondendole sotto carne di maiale. Venezia si dà un patrono e un'identità.",
 path:[[21.00,36.50],[18.50,40.10],[15.00,42.50],[12.34,45.43]]},
{id:"palermo-emirato",year:831,lat:38.12,lon:13.36,type:"fondazione",title:"Palermo capitale islamica",
 description:"Diventa la città più grande d'Italia: giardini irrigati, agrumi, canna da zucchero, e centinaia di moschee secondo i viaggiatori arabi."},
{id:"amalfi",year:900,lat:40.63,lon:14.60,type:"fondazione",title:"La repubblica di Amalfi",
 description:"Un fazzoletto di costa senza terra coltivabile diventa la prima potenza marinara italiana, con propria moneta e proprie tavole di diritto del mare."},
{id:"ungari",year:924,lat:45.19,lon:9.16,type:"disastro",title:"Gli Ungari bruciano Pavia",
 description:"Le scorrerie dall'est arrivano fino in Toscana. Le città si cingono di mura: il paesaggio urbano italiano cambia forma."},
{id:"ottone",year:962,lat:41.90,lon:12.45,type:"guerra",title:"Ottone I imperatore",
 description:"Il re di Germania scende in Italia e si fa incoronare: per otto secoli la corona imperiale e il destino italiano resteranno legati al nord delle Alpi."},

/* ==================== Comuni, Normanni, Svevi ==================== */
{id:"pisa-genova",year:1016,lat:39.22,lon:9.12,type:"guerra",title:"Pisa e Genova in Sardegna",
 description:"Le due repubbliche cacciano i Saraceni dall'isola e vi restano. È l'inizio della loro rivalità, che finirà solo in mare, alla Meloria."},
{id:"civitate",year:1053,lat:41.53,lon:15.29,type:"battaglia",title:"Civitate",
 description:"I cavalieri normanni sconfiggono e catturano papa Leone IX. Poi si inginocchiano e ne diventano vassalli: il Sud avrà un re legittimato da Roma."},
{id:"melfi",year:1059,lat:41.00,lon:15.65,type:"fondazione",title:"Il concilio di Melfi",
 description:"Roberto il Guiscardo è investito duca di Puglia, Calabria e — terra ancora da conquistare — Sicilia."},
{id:"salerno-medica",year:1060,lat:40.68,lon:14.77,type:"cultura",title:"La scuola medica salernitana",
 description:"Latini, greci, arabi ed ebrei insegnano medicina nella stessa città. Il Regimen sanitatis sarà letto in tutta Europa per secoli."},
{id:"palermo-normanna",year:1072,lat:38.12,lon:13.36,type:"guerra",title:"I Normanni a Palermo",
 description:"Ruggero e Roberto entrano in città dopo cinque mesi d'assedio. Nasce una Sicilia dove convivono notai arabi, greci e latini."},
{id:"bologna-universita",year:1088,lat:44.49,lon:11.34,type:"fondazione",title:"Lo Studio di Bologna",
 description:"Studenti che si organizzano in corporazioni e pagano i maestri: la più antica università del mondo occidentale nasce dal basso."},
{id:"crociata",year:1096,lat:44.41,lon:8.93,type:"viaggio",title:"Le flotte per la Terrasanta",
 description:"Genova, Pisa e Venezia trasportano i crociati e si fanno pagare in quartieri e privilegi nei porti d'Oriente. La crociata è anche un affare.",
 path:[[8.93,44.41],[12.33,45.44],[18.50,40.00],[21.40,36.00]]},
{id:"ruggero-ii",year:1130,lat:38.12,lon:13.36,type:"fondazione",title:"Il Regno di Sicilia",
 description:"Ruggero II unisce l'isola e il continente sotto una corona sola: sarà lo stato più moderno d'Europa, con un catasto e una burocrazia."},
{id:"cappella-palatina",year:1140,lat:38.11,lon:13.35,type:"cultura",title:"La Cappella Palatina",
 description:"Mosaici bizantini, iscrizioni arabe, soffitto a muqarnas, archi normanni: quattro civiltà nella stessa stanza, e nessuna che prevalga."},
{id:"legnano",year:1176,lat:45.60,lon:8.92,type:"battaglia",title:"Legnano",
 description:"La Lega Lombarda ferma Federico Barbarossa. Il Carroccio, altare su ruote attorno a cui ci si fa uccidere, diventa il simbolo delle libertà comunali."},
{id:"costanza",year:1183,lat:45.46,lon:9.19,type:"cultura",title:"La pace di Costanza",
 description:"L'imperatore riconosce ai Comuni il diritto di eleggere i propri consoli e di legiferare. In Italia lo stato cittadino diventa legale."},
{id:"francesco",year:1209,lat:43.07,lon:12.62,type:"cultura",title:"Francesco d'Assisi",
 description:"Un figlio di mercante si spoglia in piazza e sceglie la povertà. In dieci anni l'ordine dei minori conta migliaia di frati in tutta Europa."},
{id:"federico-ii",year:1220,lat:38.12,lon:13.36,type:"fondazione",title:"Federico II, stupor mundi",
 description:"Cresciuto a Palermo fra tre lingue, imperatore e re di Sicilia, scrive un trattato di falconeria e fonda l'università di Napoli per formarsi i funzionari."},
{id:"castel-del-monte",year:1240,lat:41.09,lon:16.27,type:"fondazione",title:"Castel del Monte",
 description:"Ottagono su ottagono, senza fossato né scuderie: più che un castello, un enigma geometrico piantato sulla Murgia."},
{id:"cortenuova",year:1237,lat:45.55,lon:9.72,type:"battaglia",title:"Cortenuova",
 description:"Federico II annienta l'esercito milanese e manda il Carroccio catturato in trionfo a Roma. La rivincita della battaglia di Legnano."},
{id:"benevento-1266",year:1266,lat:41.13,lon:14.78,type:"battaglia",title:"Benevento",
 description:"Manfredi cade combattendo contro Carlo d'Angiò. Il Sud passa ai Francesi e la capitale si sposta da Palermo a Napoli."},
{id:"tagliacozzo",year:1268,lat:42.07,lon:13.25,type:"battaglia",title:"Tagliacozzo",
 description:"Il sedicenne Corradino, ultimo degli Svevi, perde la battaglia e la testa in piazza Mercato a Napoli."},
{id:"montaperti",year:1260,lat:43.28,lon:11.44,type:"battaglia",title:"Montaperti",
 description:"I ghibellini senesi travolgono i guelfi fiorentini: \"lo strazio che fece l'Arbia colorata in rosso\", scriverà Dante."},
{id:"vespri",year:1282,lat:38.12,lon:13.36,type:"guerra",title:"I Vespri siciliani",
 description:"Un gesto di troppo di un soldato francese davanti a una chiesa, all'ora dei vespri, scatena la rivolta. In un mese l'isola è persa per gli Angioini."},
{id:"meloria",year:1284,lat:43.55,lon:10.25,type:"battaglia",title:"La Meloria",
 description:"Genova distrugge la flotta pisana: novemila prigionieri, tanti che si diceva \"per veder Pisa, andate a Genova\". Pisa non tornerà più potenza marinara."},
{id:"campaldino",year:1289,lat:43.79,lon:11.83,type:"battaglia",title:"Campaldino",
 description:"Firenze guelfa batte Arezzo. Tra i cavalieri fiorentini c'è un giovane di ventiquattro anni, Dante Alighieri."},
{id:"curzola",year:1298,lat:42.96,lon:17.13,type:"battaglia",title:"Curzola",
 description:"Genova sconfigge Venezia in Adriatico. Fra i prigionieri c'è Marco Polo, che in cella detterà a Rustichello il racconto dei suoi viaggi."},
{id:"marco-polo",year:1271,endYear:1295,lat:45.44,lon:12.33,type:"viaggio",title:"Marco Polo verso l'Oriente",
 description:"Parte a diciassette anni con il padre e lo zio, torna dopo ventiquattro. Il Milione descriverà carta moneta, carbone e poste imperiali a un'Europa incredula.",
 path:[[12.33,45.44],[16.00,41.00],[20.00,37.50],[21.40,36.20]]},

/* ==================== Trecento e Quattrocento ==================== */
{id:"dante-esilio",year:1302,lat:43.77,lon:11.26,type:"cultura",title:"L'esilio di Dante",
 description:"Condannato al rogo in contumacia, lascia Firenze per non tornarci mai. \"Tu proverai sì come sa di sale lo pane altrui\"."},
{id:"scrovegni",year:1305,lat:45.41,lon:11.88,type:"cultura",title:"Giotto agli Scrovegni",
 description:"Un banchiere paga una cappella per farsi perdonare l'usura. Giotto la riempie di figure che hanno peso, spazio e dolore umano: la pittura cambia."},
{id:"avignone",year:1309,lat:41.90,lon:12.45,type:"cultura",title:"Il papa lascia Roma",
 description:"Per settant'anni la sede pontificia è ad Avignone. Roma, senza la curia, si spopola e le sue chiese cadono a pezzi."},
{id:"commedia",year:1321,lat:44.42,lon:12.20,type:"cultura",title:"La Commedia",
 description:"Dante muore a Ravenna appena finito il Paradiso. Un poema in volgare fiorentino diventa, di fatto, la lingua italiana."},
{id:"peste-nera",year:1347,endYear:1348,lat:38.19,lon:15.55,type:"disastro",title:"La peste nera",
 description:"Arriva a Messina su navi genovesi e in due anni uccide un italiano su tre. Boccaccio la descrive dal vivo nell'introduzione al Decameron.",
 path:[[15.55,38.19],[14.27,40.85],[11.26,43.77],[9.19,45.46],[12.33,45.44]]},
{id:"cola",year:1347,lat:41.89,lon:12.48,type:"guerra",title:"Cola di Rienzo",
 description:"Un notaio si proclama tribuno e vuole restaurare la repubblica romana. Sette mesi di entusiasmo, poi la folla che lo aveva acclamato lo uccide."},
{id:"decameron",year:1353,lat:43.77,lon:11.26,type:"cultura",title:"Il Decameron",
 description:"Dieci giovani in fuga dalla peste si raccontano cento novelle. Mercanti, frati e mogli furbe entrano in letteratura al posto dei cavalieri."},
{id:"ciompi",year:1378,lat:43.77,lon:11.26,type:"guerra",title:"Il tumulto dei Ciompi",
 description:"Gli operai della lana, senza arte né rappresentanza, prendono il palazzo e governano Firenze per sei settimane."},
{id:"chioggia",year:1380,lat:45.22,lon:12.28,type:"battaglia",title:"La guerra di Chioggia",
 description:"Genova arriva a un passo dal prendere Venezia, poi resta intrappolata nella laguna e si arrende. L'Adriatico è veneziano per sempre."},
{id:"gian-galeazzo",year:1395,lat:45.46,lon:9.19,type:"fondazione",title:"Il ducato di Milano",
 description:"Gian Galeazzo Visconti compra il titolo ducale dall'imperatore e mette insieme mezza Italia settentrionale. Morirà di peste sette anni dopo, e tutto si sfalderà."},
{id:"duomo-milano",year:1386,lat:45.46,lon:9.19,type:"fondazione",title:"Il cantiere del Duomo",
 description:"Si comincia con il marmo di Candoglia portato per canali fino in centro. La fabbrica del Duomo diventerà proverbiale: finirà nell'Ottocento."},
{id:"cupola",year:1436,lat:43.77,lon:11.26,type:"fondazione",title:"La cupola di Brunelleschi",
 description:"Quarantacinque metri di diametro senza centine, con due calotte e mattoni a spina di pesce. Nessuno sapeva come si facesse: lui non lo spiegò a nessuno."},
{id:"anghiari",year:1440,lat:43.54,lon:12.06,type:"battaglia",title:"Anghiari",
 description:"Firenze batte Milano in una battaglia che Machiavelli descrive quasi senza morti. Leonardo ne dipingerà, e perderà, un affresco leggendario."},
{id:"lodi",year:1454,lat:45.31,lon:9.50,type:"cultura",title:"La pace di Lodi",
 description:"Milano, Venezia, Firenze, il Papa e Napoli si riconoscono a vicenda. Quarant'anni di equilibrio: l'Italia inventa la diplomazia degli ambasciatori stabili."},
{id:"urbino",year:1465,lat:43.73,lon:12.64,type:"cultura",title:"La corte di Urbino",
 description:"Federico da Montefeltro, capitano di ventura, si costruisce un palazzo \"in forma di città\" e una biblioteca di soli manoscritti: la stampa gli faceva schifo."},
{id:"stampa-italia",year:1465,lat:41.79,lon:12.72,type:"scoperta",title:"La stampa arriva in Italia",
 description:"Due tedeschi impiantano un torchio nel monastero di Subiaco. In vent'anni Venezia diventerà la capitale europea del libro."},
{id:"pazzi",year:1478,lat:43.77,lon:11.26,type:"battaglia",title:"La congiura dei Pazzi",
 description:"Giuliano de' Medici viene ucciso in Duomo durante la messa; Lorenzo si salva. La repressione consolida il potere mediceo."},
{id:"otranto",year:1480,lat:40.15,lon:18.49,type:"guerra",title:"I Turchi a Otranto",
 description:"La flotta ottomana prende la città e vi resta un anno. Il terrore attraversa l'Italia: si teme che Roma sia la prossima."},

/* ==================== Cinquecento ==================== */
{id:"colombo",year:1492,lat:44.41,lon:8.93,type:"viaggio",title:"Cristoforo Colombo",
 description:"Genovese al servizio di Spagna, salpa per raggiungere le Indie da ovest. Il Mediterraneo, da centro del mondo, comincia a diventare periferia.",
 path:[[8.93,44.41],[6.00,40.50],[3.60,38.50]]},
{id:"fornovo",year:1495,lat:44.69,lon:10.10,type:"battaglia",title:"Fornovo",
 description:"Carlo VIII di Francia si apre la strada del ritorno. Le guerre d'Italia sono cominciate: dureranno sessant'anni e le decideranno gli stranieri."},
{id:"cenacolo",year:1498,lat:45.47,lon:9.17,type:"cultura",title:"L'Ultima Cena",
 description:"Leonardo dipinge a secco su muro, e l'affresco comincia a rovinarsi subito. Coglie l'istante esatto in cui Cristo dice: uno di voi mi tradirà."},
{id:"savonarola",year:1498,lat:43.77,lon:11.26,type:"disastro",title:"Il rogo di Savonarola",
 description:"Il frate che aveva bruciato in piazza specchi, libri e quadri viene impiccato e arso nella stessa piazza."},
{id:"vespucci",year:1499,lat:43.77,lon:11.26,type:"viaggio",title:"Amerigo Vespucci",
 description:"Il fiorentino capisce che quelle terre non sono l'Asia ma un continente nuovo. Un cartografo tedesco lo battezzerà col suo nome."},
{id:"david",year:1504,lat:43.77,lon:11.26,type:"cultura",title:"Il David",
 description:"Michelangelo ricava da un blocco di marmo scartato da altri una figura di cinque metri. Firenze lo mette davanti a Palazzo Vecchio come avvertimento."},
{id:"agnadello",year:1509,lat:45.44,lon:9.57,type:"battaglia",title:"Agnadello",
 description:"Mezza Europa si allea nella Lega di Cambrai e Venezia perde in un giorno la terraferma. La riprenderà, ma non tornerà più quella di prima."},
{id:"sistina",year:1512,lat:41.90,lon:12.45,type:"cultura",title:"La volta della Sistina",
 description:"Quattro anni sui ponteggi, quasi sempre solo. Michelangelo, che si diceva scultore, dipinge trecento figure e la creazione del mondo."},
{id:"ravenna-1512",year:1512,lat:44.42,lon:12.20,type:"battaglia",title:"Ravenna",
 description:"La battaglia più sanguinosa delle guerre d'Italia. Vincono i Francesi, ma perdono il comandante ventiduenne Gastone di Foix e devono ritirarsi."},
{id:"marignano",year:1515,lat:45.33,lon:9.35,type:"battaglia",title:"Marignano",
 description:"Due giorni di battaglia contro i mercenari svizzeri, e l'artiglieria francese decide. Da qui gli Svizzeri sceglieranno la neutralità."},
{id:"pavia-1525",year:1525,lat:45.19,lon:9.16,type:"battaglia",title:"Pavia",
 description:"Gli archibugieri spagnoli falciano la cavalleria francese e Francesco I viene catturato. \"Tutto è perduto fuorché l'onore\"."},
{id:"sacco-roma",year:1527,lat:41.90,lon:12.46,type:"disastro",title:"Il sacco di Roma",
 description:"I lanzichenecchi senza paga saccheggiano la città per mesi. Molti storici fanno finire qui, di colpo, il Rinascimento romano."},
{id:"doria",year:1528,lat:44.41,lon:8.93,type:"fondazione",title:"Andrea Doria e Genova",
 description:"L'ammiraglio passa dalla Francia alla Spagna e dà alla città una costituzione oligarchica che durerà fino a Napoleone: Genova sceglie i soldi, non la sovranità."},
{id:"carlo-v",year:1530,lat:44.49,lon:11.34,type:"cultura",title:"L'incoronazione di Carlo V",
 description:"A San Petronio il papa incorona l'ultimo imperatore incoronato in Italia. L'egemonia spagnola sulla penisola è ufficiale."},
{id:"malta-ordine",year:1530,lat:35.90,lon:14.51,type:"fondazione",title:"I cavalieri a Malta",
 description:"Carlo V concede l'isola all'Ordine di San Giovanni per un falcone all'anno. Diventerà la sentinella cristiana del canale di Sicilia."},
{id:"concilio-trento",year:1545,endYear:1563,lat:46.07,lon:11.12,type:"cultura",title:"Il concilio di Trento",
 description:"Diciotto anni di sedute rifondano la Chiesa cattolica: seminari, catechismo, Indice dei libri proibiti. L'Italia della Controriforma nasce qui."},
{id:"siena-1555",year:1555,lat:43.32,lon:11.33,type:"guerra",title:"La caduta di Siena",
 description:"Dopo un assedio di quindici mesi l'ultima repubblica toscana si arrende. I fuoriusciti resisteranno ancora quattro anni a Montalcino."},
{id:"cateau",year:1559,lat:45.46,lon:9.19,type:"cultura",title:"Cateau-Cambrésis",
 description:"Finiscono le guerre d'Italia: la Spagna tiene Milano, Napoli, Sicilia e Sardegna. Per centocinquant'anni la penisola sarà una questione altrui."},
{id:"lepanto",year:1571,lat:38.26,lon:21.32,type:"battaglia",title:"Lepanto",
 description:"La Lega Santa, con la flotta veneziana e le galee genovesi, sconfigge gli Ottomani. Cervantes vi perde l'uso di una mano; l'Europa ritrova fiducia."},
{id:"palladio",year:1570,lat:45.55,lon:11.55,type:"cultura",title:"Palladio e le ville",
 description:"Pubblica i Quattro libri dell'architettura. Le sue ville venete verranno copiate in Inghilterra, in Russia e alla Casa Bianca."},

/* ==================== Seicento e Settecento ==================== */
{id:"bruno",year:1600,lat:41.90,lon:12.47,type:"disastro",title:"Il rogo di Giordano Bruno",
 description:"Arso vivo in Campo de' Fiori dopo otto anni di processo per aver sostenuto infiniti mondi e un universo senza centro."},
{id:"caravaggio",year:1601,lat:41.90,lon:12.47,type:"cultura",title:"Caravaggio a Roma",
 description:"Modelli presi dalla strada, piedi sporchi, luce che taglia il buio. Dipinge santi che sembrano facchini e i committenti, a volte, li rifiutano."},
{id:"orfeo",year:1607,lat:45.16,lon:10.79,type:"cultura",title:"L'Orfeo di Monteverdi",
 description:"Alla corte dei Gonzaga va in scena la prima opera che si regga ancora oggi: musica, parola e scena diventano una cosa sola."},
{id:"galileo-cannocchiale",year:1609,lat:45.41,lon:11.88,type:"scoperta",title:"Il cannocchiale di Galileo",
 description:"A Padova costruisce uno strumento venti volte più potente dei giocattoli olandesi e lo punta al cielo: montagne sulla Luna, quattro lune attorno a Giove."},
{id:"galileo-processo",year:1633,lat:41.90,lon:12.47,type:"cultura",title:"Il processo a Galileo",
 description:"Costretto ad abiurare, finisce agli arresti ad Arcetri. La scienza italiana perderà un secolo di slancio."},
{id:"peste-1630",year:1630,lat:45.46,lon:9.19,type:"disastro",title:"La peste manzoniana",
 description:"Milano perde metà degli abitanti; Venezia un terzo. Gli untori sono un'invenzione della paura, e Manzoni ne farà due secoli dopo un capitolo di storia della giustizia."},
{id:"vesuvio-1631",year:1631,lat:40.82,lon:14.43,type:"disastro",title:"Il Vesuvio si risveglia",
 description:"Dopo cinque secoli di silenzio, colate e nubi ardenti uccidono migliaia di persone nei casali alle pendici."},
{id:"masaniello",year:1647,lat:40.85,lon:14.27,type:"guerra",title:"La rivolta di Masaniello",
 description:"Una tassa sulla frutta accende Napoli. Un pescivendolo di ventisette anni comanda la città per dieci giorni, poi viene ucciso dai suoi."},
{id:"barocco-lecce",year:1660,lat:40.35,lon:18.17,type:"cultura",title:"Il barocco leccese",
 description:"La pietra tenera locale si lascia intagliare come legno: facciate di chiese che sembrano ricami, in una città di provincia dell'impero spagnolo."},
{id:"torino-1706",year:1706,lat:45.07,lon:7.69,type:"battaglia",title:"L'assedio di Torino",
 description:"Centodiciassette giorni sotto le bombe francesi; Pietro Micca fa saltare una galleria e sé stesso. I Savoia otterranno il titolo regio."},
{id:"utrecht",year:1713,lat:45.07,lon:7.69,type:"cultura",title:"La pace di Utrecht",
 description:"L'Italia spagnola passa agli Austriaci; i Savoia ottengono la Sicilia, poi scambiata con la Sardegna. Un regno, per loro, comincia da un titolo."},
{id:"vico",year:1725,lat:40.85,lon:14.26,type:"cultura",title:"La Scienza nuova di Vico",
 description:"Un professore mal pagato di Napoli sostiene che la storia ha corsi e ricorsi e che l'uomo può conoscere ciò che ha fatto. In Italia lo leggeranno tardi."},
{id:"bitonto",year:1734,lat:41.11,lon:16.69,type:"battaglia",title:"Bitonto",
 description:"Carlo di Borbone batte gli Austriaci e conquista il Regno di Napoli. Il Sud torna ad avere una corte propria dopo due secoli."},
{id:"ercolano-scavi",year:1738,lat:40.81,lon:14.35,type:"scoperta",title:"Riemerge Ercolano",
 description:"Cunicoli scavati per conto del re riportano alla luce statue e papiri carbonizzati. Nasce l'archeologia moderna, e con essa il neoclassicismo."},
{id:"pompei-scavi",year:1748,lat:40.75,lon:14.49,type:"scoperta",title:"Riemerge Pompei",
 description:"Sotto le ceneri riappaiono strade, botteghe e graffiti elettorali: non i monumenti dei re, ma la vita quotidiana di una città qualsiasi."},
{id:"paoli",year:1755,lat:42.31,lon:9.15,type:"fondazione",title:"La Corsica di Pasquale Paoli",
 description:"L'isola si dà una costituzione con separazione dei poteri e voto alle donne capofamiglia. Genova la venderà alla Francia nel 1768."},
{id:"beccaria",year:1764,lat:45.46,lon:9.19,type:"cultura",title:"Dei delitti e delle pene",
 description:"Un ventiseienne milanese sostiene che la tortura è inutile e la pena di morte ingiusta. In vent'anni mezza Europa riformerà i codici."},
{id:"reggia-caserta",year:1752,lat:41.07,lon:14.33,type:"fondazione",title:"La reggia di Caserta",
 description:"Milleduecento stanze e un acquedotto lungo trentotto chilometri per alimentare le fontane: i Borbone si costruiscono la loro Versailles."},
{id:"volta",year:1799,lat:45.81,lon:9.08,type:"scoperta",title:"La pila di Volta",
 description:"Dischi di zinco e rame separati da panno bagnato: la prima corrente elettrica continua della storia. La parola volt verrà da lì."},

/* ==================== Rivoluzione e Napoleone ==================== */
{id:"montenotte",year:1796,lat:44.35,lon:8.35,type:"battaglia",title:"Il debutto di Bonaparte",
 description:"Un generale di ventisei anni con un esercito cencioso spezza in due gli austro-piemontesi in Liguria. In un mese il Piemonte chiede l'armistizio."},
{id:"lodi-1796",year:1796,lat:45.31,lon:9.50,type:"battaglia",title:"Il ponte di Lodi",
 description:"L'assalto alla baionetta sul ponte dell'Adda diventa leggenda; i soldati cominciano a chiamarlo \"il piccolo caporale\"."},
{id:"cispadana",year:1797,lat:44.65,lon:10.93,type:"fondazione",title:"Il primo tricolore",
 description:"Il congresso della Repubblica Cispadana adotta a Reggio Emilia una bandiera verde, bianca e rossa. Diventerà la bandiera d'Italia."},
{id:"campoformio",year:1797,lat:45.96,lon:13.10,type:"guerra",title:"La fine di Venezia",
 description:"Bonaparte cede la Repubblica di San Marco all'Austria in cambio del Belgio. Mille e cento anni di indipendenza finiscono con una firma."},
{id:"partenopea",year:1799,lat:40.85,lon:14.27,type:"guerra",title:"La Repubblica Napoletana",
 description:"Cinque mesi di repubblica colta e senza popolo. Al ritorno dei Borbone, cento fra i migliori intellettuali del Regno vengono impiccati."},
{id:"marengo",year:1800,lat:44.87,lon:8.71,type:"battaglia",title:"Marengo",
 description:"Battaglia quasi perduta e ribaltata nel pomeriggio dall'arrivo di Desaix, che vi muore. Bonaparte consolida il potere a Parigi."},
{id:"regno-italico",year:1805,lat:45.46,lon:9.19,type:"fondazione",title:"Napoleone re d'Italia",
 description:"Si incorona in Duomo con la corona ferrea: \"Dio me l'ha data, guai a chi la tocca\". Codici, catasto, coscrizione: lo stato moderno arriva anche qui."},
{id:"murat",year:1808,lat:40.85,lon:14.27,type:"fondazione",title:"Gioacchino Murat a Napoli",
 description:"Il cognato di Napoleone abolisce la feudalità nel Regno. Nel 1815 tenterà l'appello agli italiani: sarà fucilato a Pizzo Calabro."},
{id:"vienna",year:1815,lat:45.07,lon:7.69,type:"cultura",title:"La Restaurazione",
 description:"Il congresso di Vienna rimette i vecchi sovrani sui troni e l'Austria a guardia di tutti. Ma il Codice napoleonico e l'idea di nazione restano."},

/* ==================== Risorgimento ==================== */
{id:"carboneria",year:1820,lat:40.85,lon:14.27,type:"guerra",title:"I moti carbonari",
 description:"Società segrete di ufficiali e borghesi ottengono una costituzione a Napoli. Durerà nove mesi, fino all'arrivo degli Austriaci."},
{id:"moti-1821",year:1821,lat:45.07,lon:7.69,type:"guerra",title:"I moti piemontesi",
 description:"Studenti e ufficiali chiedono la costituzione e la guerra all'Austria. Carlo Alberto oscilla, poi la repressione: molti in esilio, alcuni sul patibolo."},
{id:"promessi-sposi",year:1827,lat:45.85,lon:9.39,type:"cultura",title:"I promessi sposi",
 description:"Manzoni ambienta fra Lecco e Milano un romanzo di gente comune schiacciata dal potere, e sceglie il fiorentino parlato: l'italiano moderno."},
{id:"giovine-italia",year:1831,lat:44.41,lon:8.93,type:"fondazione",title:"La Giovine Italia",
 description:"Il genovese Giuseppe Mazzini fonda dall'esilio un movimento per un'Italia unita, repubblicana e indipendente. Insurrezioni fallite, idea vincente."},
{id:"moti-1831",year:1831,lat:44.65,lon:10.93,type:"guerra",title:"I moti nei ducati",
 description:"Modena, Parma e le Legazioni insorgono contando su Parigi. Parigi non arriva, e gli Austriaci sì."},
{id:"ferrovia-1839",year:1839,lat:40.85,lon:14.27,type:"fondazione",title:"Napoli-Portici",
 description:"Sette chilometri e mezzo: la prima ferrovia italiana. In vent'anni il Piemonte ne avrà più di tutti gli altri stati messi insieme."},
{id:"cinque-giornate",year:1848,lat:45.46,lon:9.19,type:"battaglia",title:"Le Cinque Giornate di Milano",
 description:"Barricate fatte di carrozze e mobili cacciano Radetzky dalla città. Per un momento sembra che l'Italia si liberi da sola."},
{id:"venezia-1848",year:1848,endYear:1849,lat:45.44,lon:12.33,type:"guerra",title:"La Repubblica di San Marco",
 description:"Daniele Manin proclama la repubblica e Venezia resiste diciassette mesi, all'assedio, al colera e al primo bombardamento aereo della storia, con palloni."},
{id:"custoza-1848",year:1848,lat:45.35,lon:10.72,type:"battaglia",title:"Custoza",
 description:"Radetzky batte i piemontesi e riprende la Lombardia. La prima guerra d'indipendenza è persa."},
{id:"repubblica-romana",year:1849,lat:41.89,lon:12.46,type:"guerra",title:"La Repubblica Romana",
 description:"Mazzini triumviro, Garibaldi sul Gianicolo, una costituzione che abolisce la pena di morte. Cadrà sotto i cannoni francesi in luglio."},
{id:"novara",year:1849,lat:45.45,lon:8.62,type:"battaglia",title:"Novara",
 description:"Sconfitto di nuovo, Carlo Alberto abdica la notte stessa e parte per il Portogallo. Il figlio Vittorio Emanuele II tiene lo Statuto."},
{id:"cavour",year:1852,lat:45.07,lon:7.69,type:"cultura",title:"Cavour al governo",
 description:"Ferrovie, banche, trattati commerciali, e un piccolo stato che si rende utile alle grandi potenze: l'unità come progetto diplomatico, non solo eroico."},
{id:"magenta",year:1859,lat:45.46,lon:8.88,type:"battaglia",title:"Magenta",
 description:"Franco-piemontesi battono gli Austriaci alle porte di Milano. Il colore del sangue sulle divise darà il nome a una tinta."},
{id:"solferino",year:1859,lat:45.37,lon:10.57,type:"battaglia",title:"Solferino e San Martino",
 description:"Quarantamila morti e feriti in un giorno. Lo svizzero Henry Dunant, di passaggio, ne resta sconvolto: da lì nascerà la Croce Rossa."},
{id:"mille",year:1860,lat:44.39,lon:8.99,type:"viaggio",title:"La spedizione dei Mille",
 description:"Mille volontari salpano da Quarto con due vapori e fucili scadenti. In cinque mesi consegnano a Vittorio Emanuele metà d'Italia.",
 path:[[8.99,44.39],[11.13,42.55],[12.44,37.80],[12.86,37.91],[13.36,38.12],[15.55,38.19],[15.65,38.11],[14.15,41.10],[14.07,41.25]]},
{id:"calatafimi",year:1860,lat:37.91,lon:12.86,type:"battaglia",title:"Calatafimi",
 description:"\"Qui si fa l'Italia o si muore\". Le camicie rosse salgono la collina alla baionetta e i borbonici cedono: la Sicilia si solleva."},
{id:"volturno",year:1860,lat:41.10,lon:14.15,type:"battaglia",title:"Il Volturno",
 description:"Ventimila garibaldini fermano l'ultimo contrattacco borbonico. La strada per Napoli è aperta."},
{id:"teano",year:1860,lat:41.25,lon:14.07,type:"cultura",title:"L'incontro di Teano",
 description:"Garibaldi consegna il Sud al re e si ritira a Caprera con un sacco di sementi. Rifiuta titoli, terre e pensione."},
{id:"regno-italia",year:1861,lat:45.07,lon:7.69,type:"fondazione",title:"Il Regno d'Italia",
 description:"Il 17 marzo Vittorio Emanuele II è proclamato re d'Italia, con capitale Torino. Mancano il Veneto, Roma e il Trentino; e, come si disse, gli italiani."},
{id:"brigantaggio",year:1861,endYear:1865,lat:40.90,lon:15.80,type:"guerra",title:"Il brigantaggio",
 description:"Nel Mezzogiorno una guerra civile mai dichiarata: più soldati impegnati che in tutte le guerre d'indipendenza, e decine di migliaia di morti."},
{id:"custoza-1866",year:1866,lat:45.35,lon:10.72,type:"battaglia",title:"Custoza, di nuovo",
 description:"L'esercito italiano perde ancora nello stesso posto. Il Veneto arriverà lo stesso, per via diplomatica: la Prussia ha vinto a Sadowa."},
{id:"lissa",year:1866,lat:43.05,lon:16.15,type:"battaglia",title:"Lissa",
 description:"La flotta italiana, più moderna e più numerosa, viene speronata e sconfitta. \"Uomini di ferro su navi di legno\", disse l'ammiraglio austriaco."},
{id:"porta-pia",year:1870,lat:41.91,lon:12.51,type:"battaglia",title:"La breccia di Porta Pia",
 description:"Tre ore di cannoneggiamento e i bersaglieri entrano a Roma. Pio IX si dichiara prigioniero in Vaticano; la questione romana durerà sessant'anni."},
{id:"roma-capitale",year:1871,lat:41.90,lon:12.48,type:"fondazione",title:"Roma capitale",
 description:"La capitale si sposta da Firenze a Roma. Una città di duecentomila abitanti, senza industria, deve diventare in fretta il centro di uno stato."},

/* ==================== Italia unita ==================== */
{id:"traforo",year:1871,lat:45.13,lon:6.70,type:"fondazione",title:"Il traforo del Frejus",
 description:"Tredici chilometri sotto le Alpi, scavati con perforatrici ad aria compressa inventate per l'occasione: l'Italia si attacca all'Europa."},
{id:"emigrazione",year:1880,endYear:1915,lat:40.85,lon:14.27,type:"viaggio",title:"La grande emigrazione",
 description:"Quattordici milioni di italiani partono in trent'anni, soprattutto dal Sud e dal Veneto. È il più grande esodo dell'Europa moderna.",
 path:[[14.27,40.85],[13.36,38.12],[10.30,42.00],[6.00,40.00],[3.60,38.00]]},
{id:"pizza-margherita",year:1889,lat:40.85,lon:14.25,type:"cultura",title:"La pizza Margherita",
 description:"Un pizzaiolo napoletano dedica alla regina una pizza coi colori della bandiera. La storia è forse ritoccata, il successo no."},
{id:"fasci-siciliani",year:1893,endYear:1894,lat:37.60,lon:13.80,type:"guerra",title:"I Fasci siciliani",
 description:"Contadini e zolfatari si organizzano per chiedere terra e contratti. Crispi manda l'esercito e proclama lo stato d'assedio."},
{id:"marconi",year:1895,lat:44.44,lon:11.29,type:"scoperta",title:"Il telegrafo senza fili",
 description:"Nella villa di famiglia sopra Bologna, un ventenne fa suonare un campanello oltre la collina, senza cavi. Il colpo di fucile del contadino conferma il segnale."},
{id:"fiat",year:1899,lat:45.07,lon:7.69,type:"fondazione",title:"Nasce la FIAT",
 description:"Trenta soci e un capitale modesto per una fabbrica di automobili a Torino. In mezzo secolo definirà la geografia industriale del paese."},
{id:"umberto",year:1900,lat:45.58,lon:9.27,type:"disastro",title:"Il regicidio di Monza",
 description:"L'anarchico Gaetano Bresci uccide Umberto I per vendicare i morti di Milano del 1898. Sale al trono Vittorio Emanuele III."},
{id:"olivetti",year:1908,lat:45.47,lon:7.88,type:"fondazione",title:"Olivetti a Ivrea",
 description:"Una fabbrica di macchine per scrivere che diventerà un esperimento sociale: mensa, biblioteca, asili, e design premiato in tutto il mondo."},
{id:"messina-1908",year:1908,lat:38.19,lon:15.55,type:"disastro",title:"Il terremoto di Messina",
 description:"Trentasette secondi e un maremoto: circa ottantamila morti fra Messina e Reggio. Il terremoto più distruttivo della storia europea."},
{id:"futurismo",year:1909,lat:45.46,lon:9.19,type:"cultura",title:"Il Manifesto futurista",
 description:"Marinetti esalta la velocità, la macchina e — purtroppo — la guerra. La prima avanguardia europea a organizzarsi come campagna pubblicitaria."},
{id:"grande-guerra",year:1915,endYear:1918,lat:45.90,lon:13.50,type:"guerra",title:"L'Italia entra in guerra",
 description:"Dodici battaglie sull'Isonzo per pochi chilometri di carso. Seicentocinquantamila morti: la generazione dei ragazzi del '99 arriva al fronte a diciotto anni."},
{id:"caporetto",year:1917,lat:46.25,lon:13.58,type:"battaglia",title:"Caporetto",
 description:"L'attacco austro-tedesco sfonda le linee e in due settimane il fronte arretra di cento chilometri. Trecentomila prigionieri, e una parola che è entrata nella lingua."},
{id:"piave",year:1918,lat:45.75,lon:12.60,type:"battaglia",title:"Il Piave",
 description:"L'esercito si riorganizza dietro il fiume e regge. In giugno la battaglia del solstizio ferma l'ultima offensiva austriaca."},
{id:"vittorio-veneto",year:1918,lat:45.98,lon:12.30,type:"battaglia",title:"Vittorio Veneto",
 description:"L'Austria-Ungheria si sfalda: l'armistizio di Villa Giusti entra in vigore il 4 novembre. Trento e Trieste sono italiane."},
{id:"fiume",year:1919,lat:45.33,lon:14.44,type:"guerra",title:"L'impresa di Fiume",
 description:"D'Annunzio occupa la città con duemila volontari e la tiene sedici mesi, con una costituzione che prevede la musica come istituzione dello stato."},
{id:"biennio-rosso",year:1920,lat:45.07,lon:7.69,type:"guerra",title:"L'occupazione delle fabbriche",
 description:"Mezzo milione di operai occupa gli stabilimenti del triangolo industriale. La paura della rivoluzione spinge borghesia e agrari verso i fasci."},
{id:"marcia-roma",year:1922,lat:41.90,lon:12.48,type:"guerra",title:"La marcia su Roma",
 description:"Squadre male armate convergono sulla capitale; il re rifiuta lo stato d'assedio e chiama Mussolini a formare il governo. Il colpo di stato è legale."},
{id:"matteotti",year:1924,lat:41.92,lon:12.47,type:"disastro",title:"Il delitto Matteotti",
 description:"Il deputato socialista che aveva denunciato i brogli viene rapito e ucciso. Dopo mesi di crisi, il regime sceglie la dittatura aperta."},
{id:"lateranensi",year:1929,lat:41.90,lon:12.45,type:"cultura",title:"I Patti Lateranensi",
 description:"Stato e Chiesa si riconoscono: nasce la Città del Vaticano e finisce la questione romana aperta nel 1870."},
{id:"bonifica",year:1932,lat:41.47,lon:12.90,type:"fondazione",title:"La bonifica pontina",
 description:"Prosciugate le paludi a sud di Roma nascono Littoria e Sabaudia, con coloni veneti e ferraresi. La malaria arretra."},
{id:"leggi-razziali",year:1938,lat:41.90,lon:12.48,type:"disastro",title:"Le leggi razziali",
 description:"Ebrei italiani espulsi da scuole, uffici e professioni. Sarà la premessa delle deportazioni del 1943-45: quasi ottomila non torneranno."},
{id:"guerra-1940",year:1940,endYear:1943,lat:41.90,lon:12.48,type:"guerra",title:"L'Italia in guerra",
 description:"Impreparata, entra nel conflitto contando su una vittoria tedesca rapida. Seguiranno Grecia, Africa, Russia e la perdita di quasi tutta la flotta."},
{id:"sbarco-sicilia",year:1943,lat:37.05,lon:14.25,type:"guerra",title:"Lo sbarco in Sicilia",
 description:"Centosessantamila uomini sulle spiagge fra Licata e Siracusa. In trentotto giorni l'isola cade e il fascismo con essa.",
 path:[[14.25,37.05],[13.36,38.12],[15.55,38.19]]},
{id:"otto-settembre",year:1943,lat:41.90,lon:12.48,type:"guerra",title:"L'8 settembre",
 description:"Annunciato l'armistizio, il governo fugge a Brindisi e l'esercito resta senza ordini. Il paese si spacca in due e comincia la guerra civile."},
{id:"quattro-giornate",year:1943,lat:40.85,lon:14.27,type:"battaglia",title:"Le Quattro Giornate di Napoli",
 description:"La città insorge da sola e caccia i tedeschi prima dell'arrivo degli Alleati: la prima grande città europea a liberarsi con le proprie forze."},
{id:"anzio",year:1944,lat:41.45,lon:12.63,type:"battaglia",title:"Lo sbarco di Anzio",
 description:"Doveva aggirare la linea Gustav in pochi giorni; diventa una testa di ponte assediata per quattro mesi."},
{id:"cassino",year:1944,lat:41.49,lon:13.83,type:"battaglia",title:"Montecassino",
 description:"Quattro battaglie e l'abbazia rasa al suolo dai bombardamenti. La sfondano i polacchi e i goumier francesi, dopo mesi e decine di migliaia di morti."},
{id:"ardeatine",year:1944,lat:41.86,lon:12.51,type:"disastro",title:"Le Fosse Ardeatine",
 description:"Per rappresaglia all'attacco di via Rasella, trecentotrentacinque uomini vengono fucilati in una cava e l'ingresso fatto saltare."},
{id:"monte-sole",year:1944,lat:44.34,lon:11.20,type:"disastro",title:"Monte Sole",
 description:"Sulle pendici fra Marzabotto e Grizzana, reparti delle SS uccidono in pochi giorni oltre settecento civili, in gran parte donne, anziani e bambini."},
{id:"liberazione",year:1945,lat:45.46,lon:9.19,type:"guerra",title:"Il 25 aprile",
 description:"Il CLN Alta Italia proclama l'insurrezione: Milano, Torino e Genova si liberano prima dell'arrivo degli Alleati."},
{id:"referendum-1946",year:1946,lat:41.90,lon:12.48,type:"fondazione",title:"Il referendum del 2 giugno",
 description:"Dodici milioni per la repubblica, dieci per la monarchia. È anche la prima volta che votano le donne italiane."},
{id:"costituzione",year:1948,lat:41.90,lon:12.48,type:"fondazione",title:"La Costituzione",
 description:"Entra in vigore il 1° gennaio, scritta insieme da cattolici, comunisti, socialisti e liberali. Nessuno di loro aveva la maggioranza da solo."},
{id:"portella",year:1947,lat:37.98,lon:13.20,type:"disastro",title:"Portella della Ginestra",
 description:"La banda Giuliano spara sui contadini riuniti per il primo maggio: undici morti. La prima strage politica della repubblica."},
{id:"polesine",year:1951,lat:45.03,lon:11.80,type:"disastro",title:"L'alluvione del Polesine",
 description:"Il Po rompe gli argini e allaga cento mila ettari. Centottantamila persone lasciano la provincia di Rovigo, molte per sempre."},
{id:"eni",year:1953,lat:41.83,lon:12.47,type:"fondazione",title:"Enrico Mattei e l'ENI",
 description:"Doveva liquidare l'AGIP, invece ci trova il metano padano e costruisce un gruppo che tratta da pari con le \"sette sorelle\"."},
{id:"trattati-roma",year:1957,lat:41.89,lon:12.48,type:"fondazione",title:"I Trattati di Roma",
 description:"In Campidoglio nasce la Comunità economica europea. L'Italia è fra i sei fondatori, e ne trarrà il mercato per il suo boom."},
{id:"boom",year:1958,endYear:1963,lat:45.46,lon:9.19,type:"cultura",title:"Il miracolo economico",
 description:"In cinque anni il reddito cresce come mai prima: Vespa, frigorifero, televisione. Due milioni di meridionali salgono al nord."},
{id:"dolce-vita",year:1960,lat:41.90,lon:12.49,type:"cultura",title:"La dolce vita",
 description:"Fellini racconta una Roma di paparazzi e feste vuote. Il film scandalizza, vince a Cannes e regala una parola a tutte le lingue del mondo."},
{id:"olimpiadi-roma",year:1960,lat:41.93,lon:12.45,type:"cultura",title:"Le Olimpiadi di Roma",
 description:"Abebe Bikila vince la maratona a piedi nudi sull'Appia antica, di notte, sotto le torce. L'Italia si mostra ricostruita."},
{id:"vajont",year:1963,lat:46.27,lon:12.33,type:"disastro",title:"Il Vajont",
 description:"Una frana annunciata cade nel bacino e scavalca la diga con un'onda di duecento metri: Longarone è cancellata, quasi duemila morti. La diga è ancora in piedi."},
{id:"autosole",year:1964,lat:44.00,lon:11.30,type:"fondazione",title:"L'Autostrada del Sole",
 description:"Settecentocinquantacinque chilometri da Milano a Napoli in otto anni, con l'Appennino traforato. Il paese si accorcia.",
 path:[[9.19,45.46],[11.34,44.49],[11.26,43.77],[12.48,41.90],[14.27,40.85]]},
{id:"alluvione-firenze",year:1966,lat:43.77,lon:11.26,type:"disastro",title:"L'alluvione di Firenze",
 description:"L'Arno invade la città con acqua e nafta. Da tutta Europa arrivano studenti a salvare libri e affreschi: gli \"angeli del fango\"."},
{id:"sessantotto",year:1968,lat:45.46,lon:9.19,type:"cultura",title:"Il Sessantotto",
 description:"Università occupate, poi l'autunno caldo delle fabbriche. Nel 1970 lo Statuto dei lavoratori porta la Costituzione dentro i cancelli."},
{id:"piazza-fontana",year:1969,lat:45.46,lon:9.19,type:"disastro",title:"Piazza Fontana",
 description:"Una bomba nella Banca dell'Agricoltura uccide diciassette persone. Comincia la strategia della tensione: dieci anni di stragi e depistaggi."},
{id:"regioni",year:1970,lat:41.90,lon:12.48,type:"fondazione",title:"Nascono le Regioni",
 description:"A ventidue anni dalla Costituzione si votano finalmente i consigli regionali ordinari. Sanità e trasporti passano al territorio."},
{id:"moro",year:1978,lat:41.90,lon:12.48,type:"disastro",title:"Il caso Moro",
 description:"Le Brigate Rosse rapiscono il presidente della DC uccidendo cinque uomini della scorta. Cinquantacinque giorni dopo, il corpo in via Caetani."},
{id:"bologna-1980",year:1980,lat:44.51,lon:11.34,type:"disastro",title:"La strage di Bologna",
 description:"Alle 10:25 del 2 agosto una bomba nella sala d'aspetto della stazione uccide ottantacinque persone. L'orologio è rimasto fermo a quell'ora."},
{id:"irpinia",year:1980,lat:40.85,lon:15.30,type:"disastro",title:"Il terremoto in Irpinia",
 description:"Novanta secondi, tremila morti, trecentomila senza casa. La ricostruzione diventerà un caso di studio su come non si spende il denaro pubblico."},
{id:"mundial",year:1982,lat:41.90,lon:12.48,type:"cultura",title:"L'Italia campione del mondo",
 description:"Dopo un girone disastroso, la squadra batte Argentina, Brasile, Polonia e Germania. Il paese scende in strada come non accadeva dal 1945."},
{id:"maxiprocesso",year:1986,endYear:1987,lat:38.12,lon:13.36,type:"cultura",title:"Il maxiprocesso di Palermo",
 description:"Quattrocentosettantacinque imputati in un'aula bunker: per la prima volta lo stato dimostra in tribunale che Cosa Nostra è un'organizzazione unitaria."},
{id:"capaci",year:1992,lat:38.15,lon:13.10,type:"disastro",title:"Capaci e via D'Amelio",
 description:"Cinquecento chili di esplosivo sotto l'autostrada uccidono Giovanni Falcone; cinquantasette giorni dopo tocca a Paolo Borsellino. La reazione del paese sarà enorme."},
{id:"mani-pulite",year:1992,endYear:1994,lat:45.46,lon:9.19,type:"cultura",title:"Mani pulite",
 description:"Da un arresto per una tangente di sette milioni di lire l'inchiesta risale a un intero sistema di finanziamento dei partiti: la Prima Repubblica finisce."},
{id:"assisi-1997",year:1997,lat:43.07,lon:12.62,type:"disastro",title:"Il terremoto in Umbria",
 description:"Crolla parte della volta della basilica superiore di Assisi durante il sopralluogo, in diretta televisiva. Restauro record in due anni."},
{id:"euro",year:2002,lat:41.90,lon:12.48,type:"cultura",title:"Arriva l'euro",
 description:"La lira esce di scena dopo centoquarant'anni. Il cambio a 1936,27 resterà a lungo un esercizio mentale quotidiano."},
{id:"laquila",year:2009,lat:42.35,lon:13.40,type:"disastro",title:"Il terremoto dell'Aquila",
 description:"Trecentonove morti e un centro storico puntellato per anni. Il processo alla Commissione grandi rischi farà discutere il mondo scientifico."},
{id:"expo",year:2015,lat:45.52,lon:9.09,type:"cultura",title:"Expo 2015",
 description:"Ventuno milioni di visitatori a Milano attorno al tema del cibo. La città ne esce come principale meta urbana del paese."},
{id:"amatrice",year:2016,lat:42.63,lon:13.29,type:"disastro",title:"Il sisma del Centro Italia",
 description:"Fra agosto e ottobre una sequenza di scosse distrugge Amatrice, Accumoli e Norcia: duecentonovantanove morti e paesi interi da ricostruire."},
{id:"codogno",year:2020,lat:45.16,lon:9.70,type:"disastro",title:"Il paziente 1 di Codogno",
 description:"Il 20 febbraio un trentottenne risulta positivo a un virus nuovo. Dieci giorni dopo la Lombardia è chiusa; poi il paese intero, primo in Occidente."},
{id:"pnrr",year:2021,lat:41.90,lon:12.48,type:"cultura",title:"Il Piano di ripresa",
 description:"Duecento miliardi europei, il più grande programma di investimenti dal dopoguerra, legati a scadenze e riforme da rispettare."},
];

if (typeof module !== 'undefined') module.exports = { EVENTI };
